# Generated by Django 4.2 on 2025-02-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Action", "액션"),
                    ("Adventure", "어드벤처"),
                    ("Animation", "애니메이션"),
                    ("Comedy", "코미디"),
                    ("Crime", "범죄"),
                    ("Documentary", "다큐멘터리"),
                    ("Drama", "드라마"),
                    ("Family", "가족"),
                    ("Fantasy", "판타지"),
                    ("History", "역사"),
                    ("Horror", "역사"),
                    ("Music", "음악"),
                    ("Mystery", "미스터리"),
                    ("Romance", "로맨스"),
                    ("Science Fiction", "SF"),
                    ("Thriller", "스릴러"),
                    ("War", "전쟁"),
                    ("Western", "서부극"),
                ],
                max_length=255,
            ),
        ),
    ]
